install.packages("factoextra")
library(factoextra)
library(cluster)
setwd("E:/data")  
data <- read.csv("cesc_log.csv", skip = 3, row.names = 1,header = FALSE)
data=t(data)
x <- as.matrix(data)
wss <- fviz_nbclust(data, kmeans, method = "wss", k.max = 10)
plot(wss)
silhouette <- fviz_nbclust(data, kmeans, method = "silhouette", k.max = 10)
plot(silhouette)